# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0a85d02450519291923b0db8656e3aa78682a0f90e3a07a3469216ab8b5117e178a8797f7c279d506491b5e771d69f22618cd9eb96940074d85239a146f0305

test:
  secret_key_base: fc84af8f92e39778e46db3e5dee0d09757741a59dd5b72bbe77facbc15a4599c6a36d91e4198e580b6b1e239ef6ee26d323ba45e83f057df6a4c5d7cd8edcadd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
